### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ernierasta** [nullgemm/excalibar#1]
Hi!
At the beginning - thank you for creating this. Excalibar looks like another interesting bar alternative.

I have few suggestions:

 - allow "tasks" to show only active window title, add option to take all free bar space,
 - allow "click" module to show output of other plugin.

Nice day!

**Comment by tsaber** [comment]
I'd like to add the option to choose whether primary or  secondary montitor as output and to be able to put it on the bottom instead of top. A short documentation on cli would leave me feeling less confused :)

looks very neat though. Just not applicable at this point to me. I'll leave it installled and will watch out for updates!

**Comment by ernierasta** [comment]
@tsaber  maybe it would be better to create separate issue? You have valuable points and this way it would be easier for author to keep track of it.
